### ISSUE TITLE
In an Android application, jmdns.impl.DNSRecord.sameValue(DNSRecord) sometimes causes a null pointer exception and crashes the hosting application.

### ISSUE THREAD

**Issue by lutusp** [rickyclarkson/jmdns#1]
Caused by the absence of try ... catch or any other safeguards to prevent the application from crashing.

I would submit my patch except that this form won't accept it. I am deeply impressed by how opaque bug reporting has become in modern times, such that it's no longer possible to submit a meaningful bug report. What an outstanding achievement.

Is anyone interested in seeing my fix for this bug, this software error, or is fixing bugs, improving computer programs, no longer thought to be important?

Hey, maybe I'll just paste my patch into this form and let you sort it out:

---

```
diff -Naur a/DNSRecord.java b/DNSRecord.java
--- a/DNSRecord.java    2015-10-30 00:41:16.000000000 -0700
+++ b/DNSRecord.java    2015-10-30 00:50:19.000000000 -0700
@@ -308,14 +308,19 @@

        @Override
        boolean sameValue(DNSRecord other) {
-           if (!(other instanceof Address)) {
+           try {
+               if (!(other instanceof Address)) {
+                   return false;
+               }
+               Address address = (Address) other;
+               if ((this.getAddress() == null) && (address.getAddress() != null)) {
+                   return false;
+               }
+               return this.getAddress().equals(address.getAddress());
+           } catch (Exception e) {
+               e.printStackTrace();
                return false;
            }
-           Address address = (Address) other;
-           if ((this.getAddress() == null) && (address.getAddress() != null)) {
-               return false;
-           }
-           return this.getAddress().equals(address.getAddress());
        }

        @Override
```

---

**Comment by rickyclarkson** [comment]
This fork is dead, I no longer use jmdns. I suggest you find the maintained repository, probably jmdns/jmdns, and send a pull request, or fork your own.
